service: expressInAWSDemo #Name of your App

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x # Node JS version
  memorySize: 512
  timeout: 15
  stage: production
  region: us-east-1 # AWS region

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
    environment:
      SENDER_EMAIL: lethanhtuan1028@gmail.com
      RECEIVER_EMAIL: lethanhtuan1028@gmail.com
